python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_train_feature_fold_0 --trlabel /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_train_label_fold_0 --tefeature /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_test_feature_fold_0 --telabel /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_test_label_fold_0 --modelfolder /home/xiao/workspace/enrich/5fold_models_topic/model_fold_0 --predictionfolder /home/xiao/workspace/enrich/5fold_prediction_topic/prediction_fold_0
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_test_label_fold_0  --predictionfolder /home/xiao/workspace/enrich/5fold_prediction_topic/prediction_fold_0 --lossf /home/xiao/workspace/enrich/5fold_loss_topic/loss_fold_0/hier_f1.txt 
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_train_feature_fold_1 --trlabel /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_train_label_fold_1 --tefeature /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_test_feature_fold_1 --telabel /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_test_label_fold_1 --modelfolder /home/xiao/workspace/enrich/5fold_models_topic/model_fold_1 --predictionfolder /home/xiao/workspace/enrich/5fold_prediction_topic/prediction_fold_1
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_test_label_fold_1  --predictionfolder /home/xiao/workspace/enrich/5fold_prediction_topic/prediction_fold_1 --lossf /home/xiao/workspace/enrich/5fold_loss_topic/loss_fold_1/hier_f1.txt 
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_train_feature_fold_2 --trlabel /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_train_label_fold_2 --tefeature /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_test_feature_fold_2 --telabel /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_test_label_fold_2 --modelfolder /home/xiao/workspace/enrich/5fold_models_topic/model_fold_2 --predictionfolder /home/xiao/workspace/enrich/5fold_prediction_topic/prediction_fold_2
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_test_label_fold_2  --predictionfolder /home/xiao/workspace/enrich/5fold_prediction_topic/prediction_fold_2 --lossf /home/xiao/workspace/enrich/5fold_loss_topic/loss_fold_2/hier_f1.txt 
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_train_feature_fold_3 --trlabel /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_train_label_fold_3 --tefeature /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_test_feature_fold_3 --telabel /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_test_label_fold_3 --modelfolder /home/xiao/workspace/enrich/5fold_models_topic/model_fold_3 --predictionfolder /home/xiao/workspace/enrich/5fold_prediction_topic/prediction_fold_3
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_test_label_fold_3  --predictionfolder /home/xiao/workspace/enrich/5fold_prediction_topic/prediction_fold_3 --lossf /home/xiao/workspace/enrich/5fold_loss_topic/loss_fold_3/hier_f1.txt 
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_train_feature_fold_4 --trlabel /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_train_label_fold_4 --tefeature /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_test_feature_fold_4 --telabel /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_test_label_fold_4 --modelfolder /home/xiao/workspace/enrich/5fold_models_topic/model_fold_4 --predictionfolder /home/xiao/workspace/enrich/5fold_prediction_topic/prediction_fold_4
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/5folddataset/train_sourceforge_topic_test_label_fold_4  --predictionfolder /home/xiao/workspace/enrich/5fold_prediction_topic/prediction_fold_4 --lossf /home/xiao/workspace/enrich/5fold_loss_topic/loss_fold_4/hier_f1.txt 
