python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/10/sf_fc_train.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/10/sf_fc_test.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/10/models --predictionfolder /home/xiao/workspace/enrich/freecode/10/prediction
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/10/prediction --lossf /home/xiao/workspace/enrich/freecode/10/loss/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/30/sf_fc_train.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/30/sf_fc_test.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/30/models --predictionfolder /home/xiao/workspace/enrich/freecode/30/prediction
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/30/prediction --lossf /home/xiao/workspace/enrich/freecode/30/loss/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/50/sf_fc_train.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/50/sf_fc_test.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/50/models --predictionfolder /home/xiao/workspace/enrich/freecode/50/prediction
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/50/prediction --lossf /home/xiao/workspace/enrich/freecode/50/loss/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/70/sf_fc_train.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/70/sf_fc_test.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/70/models --predictionfolder /home/xiao/workspace/enrich/freecode/70/prediction
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/70/prediction --lossf /home/xiao/workspace/enrich/freecode/70/loss/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/90/sf_fc_train.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/90/sf_fc_test.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/90/models --predictionfolder /home/xiao/workspace/enrich/freecode/90/prediction
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/90/prediction --lossf /home/xiao/workspace/enrich/freecode/90/loss/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/110/sf_fc_train.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/110/sf_fc_test.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/110/models --predictionfolder /home/xiao/workspace/enrich/freecode/110/prediction
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/110/prediction --lossf /home/xiao/workspace/enrich/freecode/110/loss/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/130/sf_fc_train.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/130/sf_fc_test.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/130/models --predictionfolder /home/xiao/workspace/enrich/freecode/130/prediction
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/130/prediction --lossf /home/xiao/workspace/enrich/freecode/130/loss/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/150/sf_fc_train.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/150/sf_fc_test.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/150/models --predictionfolder /home/xiao/workspace/enrich/freecode/150/prediction
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/150/prediction --lossf /home/xiao/workspace/enrich/freecode/150/loss/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/200/sf_fc_train.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/200/sf_fc_test.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/200/models --predictionfolder /home/xiao/workspace/enrich/freecode/200/prediction
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/200/prediction --lossf /home/xiao/workspace/enrich/freecode/200/loss/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/250/sf_fc_train.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/250/sf_fc_test.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/250/models --predictionfolder /home/xiao/workspace/enrich/freecode/250/prediction
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/250/prediction --lossf /home/xiao/workspace/enrich/freecode/250/loss/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/300/sf_fc_train.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/300/sf_fc_test.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/300/models --predictionfolder /home/xiao/workspace/enrich/freecode/300/prediction
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/300/prediction --lossf /home/xiao/workspace/enrich/freecode/300/loss/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/350/sf_fc_train.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/350/sf_fc_test.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/350/models --predictionfolder /home/xiao/workspace/enrich/freecode/350/prediction
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/350/prediction --lossf /home/xiao/workspace/enrich/freecode/350/loss/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/400/sf_fc_train.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/400/sf_fc_test.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/400/models --predictionfolder /home/xiao/workspace/enrich/freecode/400/prediction
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/400/prediction --lossf /home/xiao/workspace/enrich/freecode/400/loss/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/450/sf_fc_train.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/450/sf_fc_test.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/450/models --predictionfolder /home/xiao/workspace/enrich/freecode/450/prediction
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/450/prediction --lossf /home/xiao/workspace/enrich/freecode/450/loss/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/500/sf_fc_train.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/500/sf_fc_test.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/500/models --predictionfolder /home/xiao/workspace/enrich/freecode/500/prediction
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/500/prediction --lossf /home/xiao/workspace/enrich/freecode/500/loss/hier_f1.txt
