python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/10/sf_fc_train_no_idf_on_topic.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/10/sf_fc_test_no_idf_on_topic.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/10/models_no_idf_topic --predictionfolder /home/xiao/workspace/enrich/freecode/10/prediction_no_idf_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/10/prediction_no_idf_topic --lossf /home/xiao/workspace/enrich/freecode/10/loss_no_idf_topic/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/30/sf_fc_train_no_idf_on_topic.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/30/sf_fc_test_no_idf_on_topic.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/30/models_no_idf_topic --predictionfolder /home/xiao/workspace/enrich/freecode/30/prediction_no_idf_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/30/prediction_no_idf_topic --lossf /home/xiao/workspace/enrich/freecode/30/loss_no_idf_topic/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/50/sf_fc_train_no_idf_on_topic.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/50/sf_fc_test_no_idf_on_topic.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/50/models_no_idf_topic --predictionfolder /home/xiao/workspace/enrich/freecode/50/prediction_no_idf_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/50/prediction_no_idf_topic --lossf /home/xiao/workspace/enrich/freecode/50/loss_no_idf_topic/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/70/sf_fc_train_no_idf_on_topic.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/70/sf_fc_test_no_idf_on_topic.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/70/models_no_idf_topic --predictionfolder /home/xiao/workspace/enrich/freecode/70/prediction_no_idf_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/70/prediction_no_idf_topic --lossf /home/xiao/workspace/enrich/freecode/70/loss_no_idf_topic/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/90/sf_fc_train_no_idf_on_topic.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/90/sf_fc_test_no_idf_on_topic.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/90/models_no_idf_topic --predictionfolder /home/xiao/workspace/enrich/freecode/90/prediction_no_idf_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/90/prediction_no_idf_topic --lossf /home/xiao/workspace/enrich/freecode/90/loss_no_idf_topic/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/110/sf_fc_train_no_idf_on_topic.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/110/sf_fc_test_no_idf_on_topic.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/110/models_no_idf_topic --predictionfolder /home/xiao/workspace/enrich/freecode/110/prediction_no_idf_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/110/prediction_no_idf_topic --lossf /home/xiao/workspace/enrich/freecode/110/loss_no_idf_topic/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/130/sf_fc_train_no_idf_on_topic.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/130/sf_fc_test_no_idf_on_topic.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/130/models_no_idf_topic --predictionfolder /home/xiao/workspace/enrich/freecode/130/prediction_no_idf_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/130/prediction_no_idf_topic --lossf /home/xiao/workspace/enrich/freecode/130/loss_no_idf_topic/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/150/sf_fc_train_no_idf_on_topic.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/150/sf_fc_test_no_idf_on_topic.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/150/models_no_idf_topic --predictionfolder /home/xiao/workspace/enrich/freecode/150/prediction_no_idf_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/150/prediction_no_idf_topic --lossf /home/xiao/workspace/enrich/freecode/150/loss_no_idf_topic/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/200/sf_fc_train_no_idf_on_topic.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/200/sf_fc_test_no_idf_on_topic.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/200/models_no_idf_topic --predictionfolder /home/xiao/workspace/enrich/freecode/200/prediction_no_idf_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/200/prediction_no_idf_topic --lossf /home/xiao/workspace/enrich/freecode/200/loss_no_idf_topic/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/250/sf_fc_train_no_idf_on_topic.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/250/sf_fc_test_no_idf_on_topic.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/250/models_no_idf_topic --predictionfolder /home/xiao/workspace/enrich/freecode/250/prediction_no_idf_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/250/prediction_no_idf_topic --lossf /home/xiao/workspace/enrich/freecode/250/loss_no_idf_topic/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/300/sf_fc_train_no_idf_on_topic.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/300/sf_fc_test_no_idf_on_topic.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/300/models_no_idf_topic --predictionfolder /home/xiao/workspace/enrich/freecode/300/prediction_no_idf_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/300/prediction_no_idf_topic --lossf /home/xiao/workspace/enrich/freecode/300/loss_no_idf_topic/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/350/sf_fc_train_no_idf_on_topic.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/350/sf_fc_test_no_idf_on_topic.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/350/models_no_idf_topic --predictionfolder /home/xiao/workspace/enrich/freecode/350/prediction_no_idf_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/350/prediction_no_idf_topic --lossf /home/xiao/workspace/enrich/freecode/350/loss_no_idf_topic/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/400/sf_fc_train_no_idf_on_topic.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/400/sf_fc_test_no_idf_on_topic.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/400/models_no_idf_topic --predictionfolder /home/xiao/workspace/enrich/freecode/400/prediction_no_idf_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/400/prediction_no_idf_topic --lossf /home/xiao/workspace/enrich/freecode/400/loss_no_idf_topic/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/450/sf_fc_train_no_idf_on_topic.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/450/sf_fc_test_no_idf_on_topic.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/450/models_no_idf_topic --predictionfolder /home/xiao/workspace/enrich/freecode/450/prediction_no_idf_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/450/prediction_no_idf_topic --lossf /home/xiao/workspace/enrich/freecode/450/loss_no_idf_topic/hier_f1.txt
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/500/sf_fc_train_no_idf_on_topic.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/500/sf_fc_test_no_idf_on_topic.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/freecode/500/models_no_idf_topic --predictionfolder /home/xiao/workspace/enrich/freecode/500/prediction_no_idf_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/freecode/500/prediction_no_idf_topic --lossf /home/xiao/workspace/enrich/freecode/500/loss_no_idf_topic/hier_f1.txt
