#test ohloh
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/ohloh/train_sourceforge_ohloh_feature.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/ohloh/test_sourceforge_ohloh_feature.svm --telabel /home/xiao/workspace/enrich/ohloh/test_labels.txt --modelfolder /home/xiao/workspace/enrich/sf_oh_models_topic --predictionfolder /home/xiao/workspace/enrich/sf_oh_prediction_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/ohloh/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/sf_oh_prediction_topic --lossf /home/xiao/workspace/enrich/sf_oh_loss_topic/hier_f1.txt 

#test freecode
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/train_sourceforge_freecode_feature.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/test_sourceforge_freecode_feature.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/sf_fr_models_topic --predictionfolder /home/xiao/workspace/enrich/sf_fr_prediction_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/sf_fr_prediction_topic --lossf /home/xiao/workspace/enrich/sf_fr_loss_topic/hier_f1.txt

#test freecode new IDF
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/train_sourceforge_freecode_new_topic_feature.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/test_sourceforge_freecode_new_topic_feature.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/sf_fc_new_models_topic --predictionfolder /home/xiao/workspace/enrich/sf_fc_new_prediction_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/sf_fc_new_prediction_topic --lossf /home/xiao/workspace/enrich/sf_fc_new_loss_topic/hier_f1.txt

#run sourcefor on sourceforege dataset with common name as freecode
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/sourceforge/train_fc_sf_topic_sourceforge_feature.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/sourceforge/test_fc_sf_topic_sourceforge_feature.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/sf_sf_fr_models_topic --predictionfolder /home/xiao/workspace/enrich/sf_sf_fr_prediction_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/sf_sf_fr_prediction_topic --lossf /home/xiao/workspace/enrich/sf_sf_fr_loss_topic/hier_f1.txt

#run sourcefor on sourceforege dataset with common name as ohloh
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/sourceforge/train_oh_sf_topic_sourceforge_feature.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/sourceforge/test_oh_sf_topic_sourceforge_feature.svm --telabel /home/xiao/workspace/enrich/ohloh/test_labels.txt --modelfolder /home/xiao/workspace/enrich/sf_sf_oh_models_topic --predictionfolder /home/xiao/workspace/enrich/sf_sf_oh_prediction_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/ohloh/test_labels.txt  --predictionfolder /home/xiao/workspace/enrich/sf_sf_oh_prediction_topic --lossf /home/xiao/workspace/enrich/sf_sf_oh_loss_topic/hier_f1.txt

#test sourceforge on sourceforge on training set
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/sourceforge/train_sourceforge_feature.svm --trlabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --tefeature /home/xiao/workspace/enrich/sourceforge/train_sourceforge_feature.svm --telabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt --modelfolder /home/xiao/workspace/enrich/sf_models_topic --predictionfolder /home/xiao/workspace/enrich/sf_prediction_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/sourceforge/sf_labels.txt  --predictionfolder /home/xiao/workspace/enrich/sf_prediction_topic --lossf /home/xiao/workspace/enrich/sf_loss_topic/hier_f1.txt

#test freecode on freecode
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/freecode/freecode_freecode_topic_feature.svm --trlabel /home/xiao/workspace/enrich/freecode/test_labels.txt --tefeature /home/xiao/workspace/enrich/freecode/freecode_freecode_topic_feature.svm --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --modelfolder /home/xiao/workspace/enrich/fc_models_topic --predictionfolder /home/xiao/workspace/enrich/fc_prediction_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/freecode/test_labels.txt --predictionfolder /home/xiao/workspace/enrich/fc_prediction_topic --lossf /home/xiao/workspace/enrich/fc_loss_topic/hier_f1.txt

#test ohloh on ohloh
python py_new_train_hierarchical_svm.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --trfeature /home/xiao/workspace/enrich/ohloh/ohloh_ohloh_topic_feature.svm --trlabel /home/xiao/workspace/enrich/ohloh/test_labels.txt --tefeature /home/xiao/workspace/enrich/ohloh/ohloh_ohloh_topic_feature.svm --telabel /home/xiao/workspace/enrich/ohloh/test_labels.txt --modelfolder /home/xiao/workspace/enrich/oh_models_topic --predictionfolder /home/xiao/workspace/enrich/oh_prediction_topic
python py_compute_hierarchical_loss.py --hier /home/xiao/datasets/OSS_data/sf_pairwise_hierarchy.txt --telabel /home/xiao/workspace/enrich/ohloh/test_labels.txt --predictionfolder /home/xiao/workspace/enrich/oh_prediction_topic --lossf /home/xiao/workspace/enrich/oh_loss_topic/hier_f1.txt
